# Generated by Django 6.0.2 on 2026-02-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='uuid',
            new_name='id',
        ),
    ]
